language: node_js
node_js:
- '4'
- '6'
- '7'
before_install:
- npm install -g npm@3
script:
- npm run lint
- npm test
- npm run build
after_success:
- npm install coveralls
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
sudo: false
